[package]
name = "hello_alloy"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.3.0"
tokio = { version = "1.49.0", features = ["full"] }
ethers = { version = "2", features = ["abigen", "rustls"] }
eyre = "0.6"